-----------------------------------------------
--CREATE DATABASE BIBLIOTECA;
-----------------------------------------------
-- CREAR TABLAS
CREATE TABLE LECTOR(
	ID_LECTOR SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(255) NOT NULL	
);
CREATE TABLE TITULO_EDITORIAL(
	ISBN SERIAL PRIMARY KEY,
	TITULO VARCHAR(255) NOT NULL,
	EDITORIAL VARCHAR(255) NOT NULL, 
	UNIQUE(TITULO,EDITORIAL)
);
CREATE TABLE LIBRO(
	ID_LIBRO SERIAL PRIMARY KEY,
	ISBN INT NOT NULL,
	DISPONIBLE INT NOT NULL, 
	FOREIGN KEY (ISBN) REFERENCES TITULO_EDITORIAL(ISBN)
);
CREATE TABLE PRESTAMO(
	ID_PRESTAMO SERIAL PRIMARY KEY,
	ID_LECTOR INT NOT NULL,
	ID_LIBRO INT NOT NULL,
	FECHA_PRESTAMO DATE NOT NULL,
	FECHA_DEVOLUCION DATE,
	FOREIGN KEY (ID_LECTOR) REFERENCES LECTOR(ID_LECTOR),
	FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID_LIBRO)
);
-----------------------------------------------------------------